services:
  mikrotik-dns:
    container_name: mikrotik-dns
    restart: unless-stopped
    build: .
    ports:
      - "3000:3000"
      - "5354:5354/udp"
    volumes:
      - ./data:/data
    environment:
      - DNS_SERVER=${DNS_SERVER:-}
      - DATABASE_PATH=/data/queries.db
      - BACKEND_URL=http://127.0.0.1:8080
      - PORT=3000
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:3000"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
